posts:
  - 'Here are some posts: {posts}.'
  - 'Sure, I grabbed you some posts: {posts}.'
categories:
  - 'We found some categories underneath {category}. Here they are: {categories}.'
product:
  - 'We found information about {title}.'
tool:
  - 'Here is the {title}:'
category_list:
  - 'Here are some article categories you can read about: {category_list}.'
